### ISSUE TITLE
Center div

### ISSUE THREAD

**Issue by artnerdnet** [pudelmotte/sign_up_page#3]
https://github.com/pudelmotte/sign_up_page/blob/95775a6b3fca8f497024aa274a2993f6d4c1484e/index.css#L13

You can center your div and keep it in position by replacing the content of this class with:
```
margin: 0 auto;
width: fit-content;
```

This way the width will always expand or shrink depending on the internal divs and will be centered thanks to the margin: 0 auto property

**Comment by pudelmotte** [comment]
Thank you for this and all your other suggestions! This helps a lot
