### ISSUE TITLE
Suggested reading: CSS methodologies

### ISSUE THREAD

**Issue by artnerdnet** [pudelmotte/sign_up_page#5]
https://github.com/pudelmotte/sign_up_page/blob/95775a6b3fca8f497024aa274a2993f6d4c1484e/index.css#L41
You want to keep your css classes with meaningful names, so when your apps grow a lot you can still identify which is which.
I suggest you read a bit about css methodologies (I work mostly with BEM but there are a few more)

## Methodologies

**BEM**: [http://getbem.com/](http://getbem.com/)

**SMACSS**: [http://smacss.com/](http://smacss.com/)

**OOCSS**: [https://dev.to/nouran96/oocss-methodology-92d](https://dev.to/nouran96/oocss-methodology-92d)

**Comment by pudelmotte** [comment]
Going to read those now, thanks again!
